### ISSUE TITLE
scoreboard 

### ISSUE THREAD

**Issue by SamuelDRey** [SamuelDRey/GAMEGAMe-#2]
I'm trying to create a scoreboard for my game currently i have a <div id="score"></div> on my html and on my javascript i have a $(document).ready (function () {. how can i make my scoreboard collect the answers i have already in my java.

**Comment by clay-reed-a** [comment]
Sam, 

I'm very impressed w/ the work you're doing here. 

Were you able to solve this problem yet?

I'm uncertain what you mean by scoreboard, and I don't see any references to a scoreboard in the code, but... 

I am certainly able to answer many questions about Dwayne "Da Rock" Johnson. 

And the way you determined the correctness of my answers using two arrays and `indexOf` was quite clever. :clap: 

Did you want to add a _new feature_ or is this about an _existing bug_? 

Please advise. 

Clay a

**Comment by clay-reed-a** [comment]
PS -- What's wrong w/ keeping `score` inside a variable? I mean, if `questions` and `answers` are variables, why couldn't `score` be? You could even have a variable called `scores`, right?

**Comment by SamuelDRey** [comment]
Hi Clayton , 

Var score = 0;
Function guess(playerGuess){
If (playerGuess === answer){
Score= score + 1;
$('#scoreboard').text(score);
Console.log(score);
}
} 
I have this on my scripts.js . On my html 
I have the id for scoreboard to link them together . However the score board does not show on my pg . Any suggestion will be very much appreciated :) . I've been looking for this all day lol .

**Comment by clay-reed-a** [comment]
Is there an #scoreboard in your HTML?

Also. What is a pg? Can you tell me? 

Clay a

**Comment by SamuelDRey** [comment]
Yes there is a  #scoreboard .

By pg I meant  my file lol, Sorry .

**Comment by clay-reed-a** [comment]
If you still need help w/ this bug, I am gonna need you to commit your changes & push them to the repo, where I can see the code. 

Because... Well, everything you've shown me thus far is correct, so it must be something I haven't seen, and I'll only be able to find what's wrong if you show me the whole file (aka your whole pg). 

Query. Why does "pg" mean "my file lol"? 

The relationship between signifier and signified is not intuitive to me.  https://en.m.wikipedia.org/wiki/Sign_(semiotics)

Clay a

**Comment by SamuelDRey** [comment]
Hi Clayton,

I pushed my files to my repo . You can check them now and see what's the
problem. Thanks

**Comment by clay-reed-a** [comment]
Mornin' Sam, 

I have taken a look at the Java pg in your repo. 

Why not just take the logic from `guess` and put it in the `if (answer ===` conditionals you have within your listeners? 

It would seem to me you already have some logic to determine if an answer is correct, you just need to increment `score` and then display its value in your HTML, right? 

Clay a

**Comment by SamuelDRey** [comment]
So are you telling me to create another Id = score in my html then in my java set up a if (answer === conditionals with in my on click functions ?. If not please explain .

**Comment by clay-reed-a** [comment]
Sam,

Look at lines 97 and 112.

Those conditionals determine if Jabroni's answer is correct.

And if the answer is correct, it says, You're right Jaborni.

Well, if their answer is correct, you can do more than tell them they're
right, you can give them a point too.

And if you've given them a point, why not use an id in your HTML to tell
them you have given them a point?

So I guess all I'm saying is:

You've already done everything you need to do in your Java already.

You just need to do it again, but this time for points rather than
Jabronis.

Clay a

**Comment by SamuelDRey** [comment]
Is this in the right track of which you spoke off ?. If so then I can just make a div Id = points in my html . 

if (answer === "yes"){
      $("#points").html("your Right" + "++1")

```
} else {
  console.log('incorrect');
  $("#points ").html("your Wrong Jabroni" + "--1")
}
```
